### ISSUE TITLE
Accessing models issue

### ISSUE THREAD

**Issue by junaidtariq48** [langleyfoxall/xero-laravel#12]
I'm trying to access the models but it gives me error of bad method call. When i debug i was getting relationship like below
`relationshipToModelMap: array:148 [▼
    "\Accounts" => "XeroPHP\Models\Accounting\Account",
    "\Addresses" => "XeroPHP\Models\Accounting\Address"]`

and when i try `$xero->contacts()->get();` it throws bad method call exception. 

After debugging i found that when we call the contacts() it creates the key name 'contacts' but when it try to check for key in the relationshiptomodel array its not available and it throws exception.

For this issue i need to change in PrivateXeroApp.php method `populateRelationshipToModelMap` where its getting relationship by replacing below
`$relationship = Str::camel($prefix.Str::plural(str_replace([$modelsDirectory, '.php', '/'], ['', '', ''], $filename)));`
with
`$relationship = Str::camel($prefix.Str::plural(str_replace([$modelsDirectory, '.php', '\\'], ['', '', ''], $filename)));`

could you please tell me if i'm doing something wrong. I can't change directly in that file so could you please update in your repo. Thank you

**Comment by dextermb** [comment]
Hi @junaidtariq48,

By any chance are you using Windows? I suspect this could be a file system issue as we're not using the [`DIRECTORY_SEPARATOR` constant](https://www.php.net/manual/en/dir.constants.php).

As you've edited the files would you mind testing this and perhaps [opening a pull request](https://github.com/langleyfoxall/xero-laravel/compare) with this change? If not I'll update the package later today.

Thanks 👍

**Comment by dextermb** [comment]
Hi @junaidtariq48,

I've finally got a second to implement this `DIRECTORY_SEPARATOR` to resolve your issue. [Check it out](#13)!

**Comment by dextermb** [comment]
Resolved as of [`v1.2.1`](https://github.com/langleyfoxall/xero-laravel/releases/tag/v1.2.1).
