### ISSUE TITLE
Xero.php

### ISSUE THREAD

**Issue by narwy** [langleyfoxall/xero-laravel#15]
```
    public function app($key = 'default')
    {
        if (!isset($this->apps[$key])) {
            $this->apps[$key] = $this->createApp($key);
        }

        return $this->apps[$key];
    }
```

Is this worth converting to a construct on the class? That way don't have to call the `app()`?

**Comment by mikerockett** [comment]
Wouldn't think so, because it takes a key and returns the specified instance. That being said, a static constructor (IoC-driven, perhaps) would probably work well, I guess.

```php
$xero = Xero::app();
$xero = Xero::app('private');
```

That aside, this looks great, and could well be something I move to for the next phase of a project I've been working on.

**Comment by dextermb** [comment]
Closed issue as no feedback from author.
