### ISSUE TITLE
Pushing new data to Xero

### ISSUE THREAD

**Issue by kriiv** [langleyfoxall/xero-laravel#20]
I see throughout the docs that this gets data from Xero via the API. I just tried it, works great.

Does this package have the ability to push new data to Xero. ie. Create new contacts?

**Comment by dextermb** [comment]
Hi, this package is a wrapper around [XeroPHP](https://github.com/calcinai/xero-php) so whatever functionality that has you'll be able to use here.

Check out [their usage section](https://github.com/calcinai/xero-php#usage) on how to create new entities.

**Comment by DivineOmega** [comment]
Thanks for the reply here @dextermb. We should probably add this point to this package's documentation, perhaps providing a few basic examples then pointing them to XeroPHP's documentation for more detailed examples.

**Comment by accessTechnology** [comment]
@dextermb an example of how to post data using this wrapper is certainly needed please.

**Comment by dextermb** [comment]
@accessTechnology please check the examples [here](https://github.com/calcinai/xero-php#interacting-with-the-api).

**Comment by nickbluestone98** [comment]
I have been just doing the same, look at the above link that @dextermb has given you and all you need to do is just load in your required classes

`use XeroPHP\Models\Accounting\Invoice;`

        $xero = new Invoice;
