### ISSUE TITLE
Xero OAuth2 Migration 

### ISSUE THREAD

**Issue by futurewebsites** [langleyfoxall/xero-laravel#21]
Hi Xero has changed to OAuth2 and no longer supports the creation of Public and Private Apps.

https://developer.xero.com/documentation/auth-and-limits/private-applications

Does / will the repo support OAuth2 ?

**Comment by DivineOmega** [comment]
Hi there. We are planning to upgrade this library to support OAuth2.

Someone will update this issue when we have more information.

**Comment by DivineOmega** [comment]
This package is dependant on the `calcinai/xero-php` pacakge and requires it to first be updated to support OAuth2.

Related issue: https://github.com/calcinai/xero-php/issues/625.

**Comment by parkourben99** [comment]
This was recently merged https://github.com/calcinai/xero-php/pull/680

**Comment by parkourben99** [comment]
I have opened a pull request for this, https://github.com/langleyfoxall/xero-laravel/pull/24

**Comment by DivineOmega** [comment]
The initial version of this has been merged and released as v2.0.0.

The full OAuth 2 flow is being worked on, including creation of the authorisation URL and handling the redirect from Xero.
