### ISSUE TITLE
Project Directory

### ISSUE THREAD

**Issue by mikkyluchi** [langleyfoxall/xero-laravel#22]
Hi i am getting the following error
Argument 1 passed to LangleyFoxall\XeroLaravel\Utils::normalizePath() must be an instance of LangleyFoxall\XeroLaravel\string, string given, called in /var/www/html/xeroapp/vendor/langleyfoxall/xero-laravel/src/Utils.php on line 23 

Thanks

**Comment by DivineOmega** [comment]
This sounds like you may have been running on a version of PHP before `string` was accepted as a valid type cast. If you're still having the problem, could you tell us what version of PHP you are running?

**Comment by DivineOmega** [comment]
@mikkyluchi Is this still an issue for you?

**Comment by dextermb** [comment]
Closed as no response in a month. Feel free to re-open if you're still having issues :+1:
