### ISSUE TITLE
Quotes

### ISSUE THREAD

**Issue by chrisGeonet** [langleyfoxall/xero-laravel#23]
Hi

Do you have any plans to integrate the Quotes functionality recently added to the API?

https://developer.xero.com/documentation/api/quotes

**Comment by dextermb** [comment]
Hey @chrisGeonet, I believe this package is just a [Laravel](https://laravel.com/) wrapper for [`calcinai/xero-php`](https://github.com/calcinai/xero-php). Once this package supports quotes then we can bump up the dependency version and it should begin to work!

**Comment by dextermb** [comment]
Closed issue as no response in multiple months.
