### ISSUE TITLE
Invoice items (invoiceLineItems?) + bills not found

### ISSUE THREAD

**Issue by jo5ke** [langleyfoxall/xero-laravel#31]
Hello,

I've been using this package and overall I good results as expected, but now I have a problem when I want to get all bills and get all items in invoices.

I'm not sure if I'm not using the package correctly, or there is something wrong with my Xero account data, or it's methods in package are outdated, but I get next:

If I try to use "invoiceLineItems" - I get "Resource not found".

When I get all invoices with "invoices",  LineItems property is always null, even when I'm sure that I've added items on Xero invoice.

![image](https://user-images.githubusercontent.com/26692851/80548273-d513fa00-89ba-11ea-85d3-93a6dcc62aad.png)

Another problem is that I can't find method for getting all bills, I tried with "organisationBills" but I get "Resource not found", too.

**Comment by dextermb** [comment]
Hey there, this package is a Laravel wrapper for [`calcinai/xero-php`](https://github.com/calcinai/xero-php).

The data you're getting might be down to the core implementation of the invoice object. I'd advise checking if there are similar issues there- if not we can take a look at what we need to change.

Let us know how you get on!

**Comment by dextermb** [comment]
Closed issue as no response for two days. Feel free to re-open after checking the [core package](https://github.com/calcinai/xero-php) :+1:
