### ISSUE TITLE
Would love to see quotes in this.

### ISSUE THREAD

**Issue by alexhackney** [langleyfoxall/xero-laravel#5]
Great package. I use xero and would love to generate quotes from my app. Thank you for this package.

**Comment by wheatleyjj** [comment]
AFAIK the quotes entity isn't available in the Xero API as of yet - making this impossible for now.

It's an open ticket that Xero have needed to respond to for ages. Really annoying.

**Comment by DivineOmega** [comment]
Unfortunately, that's exactly correct. Quote functionality isn't available from the Xero API yet.

> The quotes functionality in Xero is not currently available via the API. If your application needs to send sales order information through to Xero we recommend you create a sales (ACCREC) invoice with a status of DRAFT.
> 
> We are planning on adding quotes functionality in future but it is not on our immediate roadmap. To help us prioritise and make sure your use case is catered for please leave your votes and comments on the Quotes User Voice page.

https://developer.xero.com/documentation/api/quotes

**Comment by DivineOmega** [comment]
@alexhackney I'm going to close this issue for now. If Xero begin to accept quotes via their API, feel free to re-open this issue or create a new one.
